### ISSUE TITLE
What kind of sorcery is this?

### ISSUE THREAD

**Issue by brian-polly** [chennavarri/aws-lambda-pandas-sample#2]
This does exactly what it says it does, contra the advice of the entire rest of the internet. Is there a guide somewhere for how this was assembled?

(Seriously, though, thank you for this.)

**Comment by chennav** [comment]
@brian-polly there is documentation lying around on AWS site but that doesn't really give all the details. This is the specific reason why I've uploaded this. AWS documentation is good on a higher level but when you want to do customized things you really have to scramble through the internet for examples.

**Comment by brian-polly** [comment]
@chennav that makes a lot of sense.

What did you do to get the .so files into the package directories? It'd be really nice to do this with a couple of other extension modules (scikit, cvxopt...)
